variable "regions" {
  type = "map"

  description = "Azure region mapping between short and standard format."

  default = {
    us-west          = "West US"
    us-west-2        = "West US 2"
    us-west-central  = "West Central US"
    us-south-central = "South Central US"
    us-north-central = "North Central US"
    us-east          = "East US"
    us-east-2        = "East US 2"
    can-central      = "Canada Central"
    can-east         = "Canada East"
    bra-south        = "Brasil South"
    uk-south         = "UK South"
    uk-west          = "UK West"
    eu-north         = "North Europe"
    eu-west          = "West Europe"
    fr-central       = "France Central"
    fr-south         = "France South"
    ger-neast        = "Germany Northeast"
    ger-central      = "Germany Central"
    saf-west         = "South Africa West"
    saf-north        = "South Africa North"
    ind-west         = "West India"
    ind-central      = "Central India"
    ind-south        = "South India"
    asia-southeast   = "Southeast Asia"
    asia-east        = "East Asia"
    ch-north         = "China North"
    ch-east          = "China East"
    kor-central      = "Korea Central"
    kor-south        = "Korea South"
    jap-east         = "Japan East"
    jap-west         = "Japan West"
    aus-central      = "Australia Central"
    aus-central-2    = "Australia Central 2"
    aus-east         = "Australia East"
    aus-southeast    = "Australia Southeast"
  }
}
