name: Bug Report
description: If something isn't working as expected.
title: "[BUG] ..."
labels: [bug]
body:
  - type: textarea
    id: community
    attributes:
      label: Community Note
      description: This note is for the community, please leave and skip this.
      value: |
        <!--- Please keep this note for the community --->

        * Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
        * Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
        * If you are interested in working on this issue or have submitted a pull request, please leave a comment

        <!--- Thank you for keeping this note for the community --->
    validations:
      required: true
  - type: input
    id: terraform
    attributes:
      label: OpenTofu Version
      description: Which OpenTofu/Terraform version are you using?
      placeholder: 1.9.0
    validations:
      required: true
  - type: input
    id: azurerm
    attributes:
      label: AzureRM Provider Version
      description: Which AzureRM Provider version are you using?
      placeholder: 4.0.0
    validations:
      required: true
  - type: input
    id: resource
    attributes:
      label: Affected Resource(s)/Data Source(s)
      description: Please list the affected resources and/or data sources.
      placeholder: azurerm_XXXXX
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: OpenTofu Configuration Files
      description: |
        Please provide a minimal OpenTofu/HCL code configuration that can reproduce the issue.

        For large OpenTofu configs, please use a public Github repository.
      render: hcl
    validations:
      required: true
  - type: textarea
    id: debug
    attributes:
      label: Debug Output/Panic Output
      description: |
        For long debug logs please provide a link to a GitHub Gist containing the complete debug output. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

        To obtain the debug output, see the  [OpenTofu documentation on debugging](https://opentofu.org/docs/internals/debugging/) or [Terraform documentation on debugging](https://www.terraform.io/docs/internals/debugging.html).
      render: shell
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: What should have happened?
  - type: textarea
    id: actual
    attributes:
      label: Actual Behaviour
      description: What actually happened?
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Please list the steps required to reproduce the issue, e.g:

        1. `tofu apply`
  - type: input
    id: facts
    attributes:
      label: Important Factoids
      description: |
        Are there anything atypical about your accounts that we should know? For example: Running in a Azure China/Germany/Government?
  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

        Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Such as vendor documentation?
